export const PERMISSIONS = {
  // Navigation / View Permissions
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_COURTS: 'VIEW_COURTS',
  VIEW_CASES: 'VIEW_CASES',
  VIEW_DISCOVERY: 'VIEW_DISCOVERY',
  VIEW_SYNC: 'VIEW_SYNC',
  VIEW_DOCUMENTS: 'VIEW_DOCUMENTS',
  VIEW_SEARCH: 'VIEW_SEARCH',
  VIEW_API_USAGE: 'VIEW_API_USAGE',
  VIEW_FAILURES: 'VIEW_FAILURES',
  VIEW_SETTINGS: 'VIEW_SETTINGS',
  VIEW_USERS: 'VIEW_USERS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  VIEW_SYSTEM_HEALTH: 'VIEW_SYSTEM_HEALTH',

  // Operational Action Permissions
  START_DISCOVERY: 'START_DISCOVERY',
  PAUSE_DISCOVERY: 'PAUSE_DISCOVERY',
  RESUME_DISCOVERY: 'RESUME_DISCOVERY',
  CANCEL_DISCOVERY: 'CANCEL_DISCOVERY',
  RETRY_DISCOVERY: 'RETRY_DISCOVERY',

  START_SYNC: 'START_SYNC',
  RETRY_SYNC: 'RETRY_SYNC',
  SYNC_COURTS: 'SYNC_COURTS',
  SYNC_CASES: 'SYNC_CASES',

  // Administrative Permissions
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',

  // Sensitive API & Raw Data Permissions
  VIEW_RAW_API_DATA: 'VIEW_RAW_API_DATA',
  VIEW_API_CREDENTIAL_CONFIGURATION: 'VIEW_API_CREDENTIAL_CONFIGURATION',
};
